### ISSUE TITLE
iOS10 setting title attributes causes title hidden

### ISSUE THREAD

**Issue by yudun1989** [HeshamMegid/HMSegmentedControl#203]
self.control.titleTextAttributes = @{NSForegroundColorAttributeName : [UIColor blackColor],  NSFontAttributeName:[UIFont systemFontOfSize:14]};
    self.control.selectedTitleTextAttributes = @{NSForegroundColorAttributeName : [UIColor blueColor], NSFontAttributeName:[UIFont systemFontOfSize:14]};
    [self.control setSectionTitles:@[@"hello", @"loha", @"aloha"]];

title disappears after set title TextAttributes

**Comment by loumzy** [comment]
i have the same problem. this bug comes when title is short. for example, title hides when it sames like "全部" but show again when it becomes "全部订单"

**Comment by loumzy** [comment]
there may something wrong when setting title to the segment.
 when title font is big like 20.0f, the bug don't  show, but when font is small like 12.0f, the bug shows.

**Comment by yudun1989** [comment]
@loumzy 
https://github.com/HeshamMegid/HMSegmentedControl/pull/202

**Comment by davroux** [comment]
It seems to also occur on iOS 9.x. We have some short title disappearing in our release app.

**Comment by HeshamMegid** [comment]
Hey everyone,

Please check the Swift version of HMSegmentedControl at https://github.com/HeshamMegid/HMSegmentedControl-Swift/.

It should solve this issue.

**Comment by rutger588** [comment]
@HeshamMegid 
Is this issue going to be fixed in the ObjC version? Since I'm using `MXSegmentedPager` which uses this library as dependency

**Comment by davroux** [comment]
Same, we are using in a lot of our VC.

**Comment by yudun1989** [comment]
@rutger588 @davroux  HeshamMegid had merged the branch which already fixed this issue https://github.com/HeshamMegid/HMSegmentedControl/pull/202

**Comment by maarek** [comment]
Pulling in master did not fix this issue for me. The title label seems to be missing completely on iOS 10 when viewed from the View Hierarchy.

**Comment by NorwaySmith** [comment]
Title not shown when build with iOS 10.0 .

**Comment by lp380490944** [comment]
thank  you . now solved my problem!
