### ISSUE TITLE
Section titles does not display under iOS10(compatible bug)

### ISSUE THREAD

**Issue by lotushacker** [HeshamMegid/HMSegmentedControl#215]
### Hi： 
- I  have set section titles for  my segmentedControl like code below:
```java
NSArray* titleArray = @[titleOne, titleTwo];
  
    self.segmentCtl = [[AMCustomSegmentedControl alloc] initWithSectionTitles:titleArray];
    [self.segmentCtl setFrame:CGRectMake(0, 0, SCREEN_WIDTH, 42.0f)];
    self.segmentCtl.selectedSegmentIndex = 0;
    self.segmentCtl.selectionIndicatorLocation = AMSegmentedControlSelectionIndicatorLocationDown;
    self.segmentCtl.segmentWidthStyle = AMSegmentedControlSegmentWidthStyleFixed;
    self.segmentCtl.selectionIndicatorColor = [UIColor colorWithRGB:0xE64322];
    self.segmentCtl.selectionStyle = AMSegmentedControlSelectionStyleFullWidthStripe;
    self.segmentCtl.selectionIndicatorHeight = 2.0f;
    self.segmentCtl.borderType = AMSegmentedControlBorderTypeBottom;
    self.segmentCtl.borderColor = [UIColor colorWithRGB:0xE5E5E5];
    self.segmentCtl.titleTextAttributes = @{NSFontAttributeName: SYSTEMFONT(15.0f), NSForegroundColorAttributeName: [UIColor colorWithRGB:0x757575]};
    self.segmentCtl.selectedTitleTextAttributes = @{NSFontAttributeName: SYSTEMFONT(15.0f), NSForegroundColorAttributeName: [UIColor colorWithRGB:0xE64322]};
    [self.segmentCtl addTarget:self action:@selector(segmentChanged:) forControlEvents:UIControlEventValueChanged]
```

- however, titles does not display under iOS10(as shown below), and everything is well with other versions of system. Anyone can supply some feasible advise or fix this? Thx a lot.
![img_0027](https://cloud.githubusercontent.com/assets/16223730/18223478/d8da5364-71ea-11e6-864f-435c979b8d96.jpg)

**Comment by jayhe** [comment]
This issue is fixed with version 1.5.3

**Comment by lotushacker** [comment]
Thx, perfectly fix.

**Comment by doggy00792** [comment]
When will it get updated to 1.5.3 on CocoaPods?

**Comment by ZackTvZ** [comment]
CocoaPods still 1.5.2?

**Comment by roadst3r** [comment]
Any news on this subject?
CocoaPods still doesn't update to 1.5.3

**Comment by MiracleJ** [comment]
CocoaPods still doesn't update to 1.5.3

**Comment by Oggerschummer** [comment]
Same issue for me, pod is not updating

**Comment by btrzupek** [comment]
It looks like the pod spec file in the 1.5.3 tag is still 'displaying' 1.5.2

**Comment by btrzupek** [comment]
Pod now updated and the control works correctly with:
pod 'HMSegmentedControl', :git =>'https://github.com/HeshamMegid/HMSegmentedControl.git', :tag => '1.5.3'

However, CocoaPods still says it is version 1.5.2

**Comment by CodeY2J** [comment]
CocoaPods still says it's version 1.5.2,even though i use this command pod 'HMSegmentedControl', :git =>'https://github.com/HeshamMegid/HMSegmentedControl.git', :tag => '1.5.3',please tell me how to update this to version 1.5.3

**Comment by btrzupek** [comment]
CodeY2J, I had the same experience. I believe that the code branch pointed to by the github URL is correct for the 1.5.3 tag, but inside that branch, in the pod spec file, it still says it is version 1.5.2.

So, after pod install(ing) from the above URL and rebuilding my project - everything worked just fine - despite cocoa pods still saying it is 1.5.2.

**Comment by Agoer** [comment]
tag for 1.5.3 can not update success。。

**Comment by HeshamMegid** [comment]
Sorry folks, I pushed the wrong tag name then travelled for a week with no internet access! 😬

It should be fixed now.

**Comment by andrewjburnett** [comment]
I'm still met with an error.

None of your spec sources contain a spec satisfying the dependency: HMSegmentedControl (~> 1.5.3).

**Comment by alims** [comment]
not displaye. I'm still met with an error. v1.5.3

**Comment by osolano** [comment]
I also still have the same issue and on v1.5.3
